Artefakt 1: Moduł Zbierania Danych, Analizy i Rekonesansu
Pierwszym, fundamentalnym produktem platformy NoiseForge jest zintegrowany Moduł Zbierania Danych oraz Analizy i Rekonesansu. Jego głównym zadaniem jest agregowanie, precyzyjna normalizacja oraz bezpieczne przechowywanie wejściowych logów, informacji o zdarzeniach oraz adresów IP, z których platforma będzie korzystać w kolejnych etapach działania. Artefakt ten stanowi mózg operacyjny całego systemu, przygotowując rzetelny profil celu. Wykorzystuje do tego zaawansowane skrypty napisane w języku Python oraz silnik Apache Spark, który pozwala na rozproszone i wysoce zoptymalizowane przetwarzanie niezwykle dużych zbiorów danych (Big Data) napływających w czasie rzeczywistym. Zebrane informacje trafiają następnie do warstwy analitycznej. Składa się ona z relacyjnych baz PostgreSQL, obsługujących z ustrukturyzowane dane konfiguracyjne, oraz klastrów Elasticsearch, które odpowiadają za błyskawiczne indeksowanie milionów wierszy logów systemowych. Wszystko to oparte jest na potężnej chmurze obliczeniowej i stanowi koncepcję Data Lake.
Z perspektywy operacyjnej, opisywany moduł odpowiada za analizę metodą OSINT (Open-Source Intelligence), głęboką identyfikację powierzchni ataku w docelowej infrastrukturze oraz klasyfikację potencjalnych scenariuszy, które mogą zostać zasymulowane w późniejszym etapie. System ten musi operować na olbrzymich zbiorach informacji, dlatego analityk systemowy czuwa nad poprawnością zapytań i integralnością logiki parsującej wpisy. Z uwagi na specyfikę środowiska cyberbezpieczeństwa, moduł ten jest obarczony wysokim ryzykiem naruszeń, co narzuca na inżynierów konieczność wdrożenia szeregu wyśrubowanych mechanizmów kontrolnych. Wzorując się na przyjętej metodyce definiowania wymagań systemowych, zidentyfikowano następujące ryzyka i odpowiadające im klauzule technologiczno-biznesowe:
•	R1: Nieuczciwy klient wykorzysta system analizy by potajemnie zeskanować i zaatakować inny podmiot. Narzędzia OSINT i skanery sieciowe zaimplementowane w module mogą posłużyć do nielegalnego rekonesansu cudzej infrastruktury bez wiedzy właściciela.
•	WB1. Przed podpisaniem umowy wdrożeniowej z klientem oraz udostępnieniem mu interfejsu systemu, rygorystycznie zweryfikowane zostaną uprawnienia prawne i techniczne (np. poprzez wpisy DNS TXT lub poświadczenia notarialne) do skanowanych adresów IP oraz przestrzeni domenowych.
•	WB2. Umowa o świadczenie usług platformy NoiseForge musi obligatoryjnie zawierać klauzule dot. odpowiedzialności cywilno-prawnej oraz odwołania do Kodeksu Karnego za próbę użycia narzędzia poza dozwolonym zakresem.
•	R2: System analityczny nie wykryje kluczowych podatności lub błędnie zidentyfikuje architekturę sieciową. Braki w logice skanerów mogą sprawić, że część infrastruktury zostanie pominięta, co zaburzy cały proces symulacji ataku i doprowadzi do błędnej klasyfikacji scenariuszy.
•	WB3. Wybrany do analizy i normalizacji silnik analityczny zostanie uprzednio dogłębnie sprawdzony i przetestowany w zamkniętym środowisku. Skrypty klasyfikujące w Pythonie będą wymagały ciągłego utrzymania i stałych aktualizacji sygnatur przez specjalistów bezpieczeństwa.
•	WB4. Umowa SLA (Service Level Agreement) ma zawierać wyraźne klauzule dot. braku gwarancji na stuprocentowe, bezbłędne mapowanie całej nieudokumentowanej infrastruktury. System wykrywa tylko to, co jest eksponowane na powierzchnię.
•	R3: System analityczny będzie zbyt długo przetwarzał ogromne zbiory danych lub testował pojedyncze adresy. Wynika to z opóźnień sieciowych oraz limitów odpowiedzi po stronie badanej infrastruktury, co może zablokować zasoby obliczeniowe całej platformy chmurowej.
•	WW1. Umowa ma zawierać rygorystyczne klauzule dot. maksymalnego przewidywanego czasu skanowania pojedynczego adresu IP lub podsieci. Jeśli węzeł w architekturze (np. load balancer) nie odpowiada w ustalonym czasie, sesja jest zrywana.
•	WW2. Kod modułu będzie posiadał zaszyte na sztywno ograniczenia ilości jednoczesnych wątków. Umowa z klientem określi limity ilości jednocześnie skanowanych adresów oraz przewidzi scenariusze na wypadek wykrycia licznych maszyn wirtualnych schowanych za pojedynczymi adresami IP publicznymi (tzw. NAT).
Aby środowisko było całkowicie odporne na zewnętrzne manipulacje, Moduł Zbierania Danych musi operować w ścisłej izolacji sieciowej. Zastosowanie systemu typu SIEM (jak zadeklarowany Splunk lub struktura ELK Stack) gwarantuje, że wszelkie anomalie podczas pracy samego modułu zostaną natychmiast zarejestrowane w logach systemowych.
